[platformio]
libdeps_dir = C:\Users\AXIOO\.pio_libdeps

[env:lolin_s2_mini]
platform = espressif32
board = lolin_s2_mini
framework = arduino
monitor_speed = 115200
lib_ldf_mode = deep+
board_build.filesystem = littlefs

# Wajib agar serial monitor mendeteksi output USB Native S2 Mini
build_flags = 
    -DARDUINO_USB_CDC_ON_BOOT=1

lib_deps =
    https://github.com/mobizt/Firebase-ESP-Client.git
    bblanchon/ArduinoJson @ ^6.21.4
    FS
    LittleFS

